import React from 'react';
import { Link, useLocation } from 'react-router-dom';
import { Brain, LayoutDashboard, PlusCircle, History, FileText, User, LogOut, Sparkles } from 'lucide-react';
import { useApp } from '../context/AppContext';

const navItems = [
  { to: '/dashboard', label: 'Dashboard', icon: LayoutDashboard },
  { to: '/start-interview', label: 'New Interview', icon: PlusCircle },
  { to: '/history', label: 'History', icon: History },
  { to: '/resume', label: 'Resume Builder', icon: FileText },
  { to: '/profile', label: 'Profile', icon: User },
];

export default function Sidebar() {
  const location = useLocation();
  const { user, logout } = useApp();

  const initials = user?.name
    ? user.name.split(' ').map(w => w[0]).join('').toUpperCase().slice(0, 2)
    : 'U';

  return (
    <aside className="hidden md:flex fixed top-0 left-0 h-full w-60 flex-col z-30 sidebar-gradient">
      {/* Logo */}
      <div className="flex items-center gap-2.5 px-5 h-16 border-b" style={{borderColor:'rgba(255,255,255,0.06)'}}>
        <div className="w-8 h-8 rounded-xl bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center shadow-lg" style={{boxShadow:'0 4px 12px rgba(99,102,241,0.4)'}}>
          <Brain className="w-4.5 h-4.5 text-white" style={{width:'18px',height:'18px'}} />
        </div>
        <span className="font-black text-white text-base">InterviewAI</span>
      </div>

      {/* Nav */}
      <nav className="flex-1 px-3 py-4 space-y-0.5">
        <p className="text-slate-600 text-xs font-semibold uppercase tracking-wider px-3 mb-3">Menu</p>
        {navItems.map(({ to, label, icon: Icon }) => {
          const active = location.pathname === to || (to !== '/dashboard' && location.pathname.startsWith(to));
          return (
            <Link key={to} to={to}
              className={`flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-medium transition-all duration-200 group ${
                active
                  ? 'nav-item-active text-indigo-300'
                  : 'text-slate-500 hover:text-slate-200 hover:bg-white/4'
              }`}
              style={active ? {} : {}}>
              <Icon className={`w-4.5 h-4.5 transition-colors ${active ? 'text-indigo-400' : 'text-slate-600 group-hover:text-slate-300'}`}
                style={{width:'18px',height:'18px'}} />
              {label}
              {to === '/start-interview' && (
                <span className="ml-auto text-xs bg-indigo-500/20 text-indigo-400 px-1.5 py-0.5 rounded-md font-semibold">New</span>
              )}
            </Link>
          );
        })}
      </nav>

      {/* AI Banner */}
      <div className="mx-3 mb-3 p-4 rounded-2xl relative overflow-hidden"
        style={{background:'linear-gradient(135deg, rgba(99,102,241,0.2), rgba(139,92,246,0.15))', border:'1px solid rgba(99,102,241,0.25)'}}>
        <div className="absolute top-0 right-0 opacity-20">
          <Sparkles className="w-16 h-16 text-indigo-400" />
        </div>
        <p className="text-white text-xs font-bold mb-1 relative z-10">AI-Powered</p>
        <p className="text-slate-400 text-xs relative z-10 leading-relaxed">Questions generated by Google Gemini</p>
      </div>

      {/* User footer */}
      <div className="px-3 pb-4 border-t pt-3" style={{borderColor:'rgba(255,255,255,0.06)'}}>
        <div className="flex items-center gap-3 px-3 py-2 rounded-xl mb-2"
          style={{background:'rgba(255,255,255,0.03)'}}>
          <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center text-white font-bold text-xs flex-shrink-0">
            {initials}
          </div>
          <div className="min-w-0">
            <p className="text-white text-sm font-semibold truncate">{user?.name}</p>
            <p className="text-slate-500 text-xs truncate">{user?.email}</p>
          </div>
        </div>
        <button onClick={logout}
          className="w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-slate-500 hover:text-red-400 hover:bg-red-500/8 text-sm transition-all">
          <LogOut style={{width:'16px',height:'16px'}} />
          Sign Out
        </button>
      </div>
    </aside>
  );
}
